## Binary Classification using Logistic Regression

In [1]:
# importing basic libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# creating a dataset

from sklearn.datasets import make_classification
X,y=make_classification(n_features=10, n_samples=1000, n_classes=2,  random_state=42)

In [4]:
pd.DataFrame(X)

NameError: name 'pd' is not defined

In [4]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [5]:
# splitting the data into train, test sets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y)

In [6]:
# training our Logistic Regression Model

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [7]:
y_pred=model.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1])

In [8]:
model.predict_proba(X_test)

array([[9.78987346e-01, 2.10126538e-02],
       [8.26736592e-01, 1.73263408e-01],
       [9.42341331e-01, 5.76586688e-02],
       [5.92638978e-01, 4.07361022e-01],
       [4.66155588e-02, 9.53384441e-01],
       [9.75722386e-01, 2.42776142e-02],
       [8.60467413e-01, 1.39532587e-01],
       [4.58297304e-02, 9.54170270e-01],
       [9.38574822e-01, 6.14251785e-02],
       [7.30568198e-02, 9.26943180e-01],
       [9.81955671e-01, 1.80443289e-02],
       [1.70172647e-01, 8.29827353e-01],
       [5.05201600e-02, 9.49479840e-01],
       [5.60901033e-01, 4.39098967e-01],
       [5.81556274e-01, 4.18443726e-01],
       [2.52834254e-04, 9.99747166e-01],
       [9.63903016e-01, 3.60969840e-02],
       [9.03420112e-01, 9.65798877e-02],
       [8.48758400e-01, 1.51241600e-01],
       [2.22818908e-04, 9.99777181e-01],
       [7.59949638e-04, 9.99240050e-01],
       [4.54894803e-02, 9.54510520e-01],
       [1.91277901e-01, 8.08722099e-01],
       [6.61549579e-01, 3.38450421e-01],
       [9.472249

In [9]:
# validating the performance of our model using Performance Metrics

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
accuracy=accuracy_score(y_test, y_pred)
cm=confusion_matrix(y_test, y_pred)
p_score=precision_score(y_test, y_pred)
r_score=recall_score(y_test, y_pred)
print(f"Accuracy: {accuracy}\nConfusion Matrix: \n{cm}\nPrecision Score: {p_score}\nRecall Score: {r_score}")

Accuracy: 0.868
Confusion Matrix: 
[[116  11]
 [ 22 101]]
Precision Score: 0.9017857142857143
Recall Score: 0.8211382113821138


In [10]:
# checking the classification report of our model

from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(f"Classification Report:\n{cr}")

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.91      0.88       127
           1       0.90      0.82      0.86       123

    accuracy                           0.87       250
   macro avg       0.87      0.87      0.87       250
weighted avg       0.87      0.87      0.87       250



In [13]:
# Hyper-Parameter Evaluation

log_reg=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
params=dict(penalty=penalty,C=c_values, solver=solver)

In [14]:
# Hyper-Parameter Tuning: Grid-Search CV

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold(n_splits=5, shuffle=False)
grid=GridSearchCV(estimator=log_reg, param_grid=params, scoring='accuracy',cv=cv, n_jobs=-1)

In [15]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [16]:
grid.fit(X_train, y_train)

/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: T

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [17]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}

In [18]:
grid.best_score_

np.float64(0.8653333333333333)

In [22]:
y_pred=grid.predict(X_test)

In [23]:
# evalidating the performance of our Grid CV model using Performance Metrics

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
accuracy=accuracy_score(y_test, y_pred)
cm=confusion_matrix(y_test, y_pred)
p_score=precision_score(y_test, y_pred)
r_score=recall_score(y_test, y_pred)
print(f"Accuracy: {accuracy}\nConfusion Matrix: \n{cm}\nPrecision Score: {p_score}\nRecall Score: {r_score}")

Accuracy: 0.876
Confusion Matrix: 
[[117  10]
 [ 21 102]]
Precision Score: 0.9107142857142857
Recall Score: 0.8292682926829268


In [24]:
# checking the classification report of our Grid CV model

from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(f"Classification Report:\n{cr}")

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.92      0.88       127
           1       0.91      0.83      0.87       123

    accuracy                           0.88       250
   macro avg       0.88      0.88      0.88       250
weighted avg       0.88      0.88      0.88       250



In [25]:
# Hyper-Parameter Tuning: Randomized Search CV

from sklearn.model_selection import RandomizedSearchCV
rscv=RandomizedSearchCV(estimator=model, param_distributions=params, scoring='accuracy', n_jobs=-1, cv=5)

In [26]:
rscv.fit(X_train, y_train)

/opt/miniconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/miniconda3/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    so

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [27]:
rscv.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 0.01}

In [28]:
rscv.best_score_

np.float64(0.8653333333333333)

In [29]:
y_pred=rscv.predict(X_test)

In [30]:
# evalidating the performance of our Randomized Search CV model using Performance Metrics

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
accuracy=accuracy_score(y_test, y_pred)
cm=confusion_matrix(y_test, y_pred)
p_score=precision_score(y_test, y_pred)
r_score=recall_score(y_test, y_pred)
print(f"Accuracy: {accuracy}\nConfusion Matrix: \n{cm}\nPrecision Score: {p_score}\nRecall Score: {r_score}")

Accuracy: 0.876
Confusion Matrix: 
[[117  10]
 [ 21 102]]
Precision Score: 0.9107142857142857
Recall Score: 0.8292682926829268


In [32]:
# checking the classification report of our Randomized Search CV model

from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(f"Classification Report:\n{cr}")

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.92      0.88       127
           1       0.91      0.83      0.87       123

    accuracy                           0.88       250
   macro avg       0.88      0.88      0.88       250
weighted avg       0.88      0.88      0.88       250

