### Plotting ROC AUC Curve using Logistic Regression

In [2]:
# importing required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# importing libraries for roc curve and auc

from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [4]:
# generate a dataset with 2 classes

X,y=make_classification(n_samples=1000, n_classes=2, random_state=1)

In [5]:
# splitting the dataset into training and test sets

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2)

In [6]:
# dummy model with default 0 as output

dummy_prob=[0 for _ in range(len(y_test))]
dummy_prob

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [7]:
# let's create a basic Logistic Regression Model

model=LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [8]:
# prediction based on probability

y_pred_proba=model.predict_proba(X_test)
y_pred_proba

array([[0.1862458 , 0.8137542 ],
       [0.02644191, 0.97355809],
       [0.99209965, 0.00790035],
       [0.72280486, 0.27719514],
       [0.69075279, 0.30924721],
       [0.05692203, 0.94307797],
       [0.16065834, 0.83934166],
       [0.10097191, 0.89902809],
       [0.98338523, 0.01661477],
       [0.18096876, 0.81903124],
       [0.58520142, 0.41479858],
       [0.98671052, 0.01328948],
       [0.11734451, 0.88265549],
       [0.26248936, 0.73751064],
       [0.98041919, 0.01958081],
       [0.19353729, 0.80646271],
       [0.96242022, 0.03757978],
       [0.60846477, 0.39153523],
       [0.03355564, 0.96644436],
       [0.99630185, 0.00369815],
       [0.36525552, 0.63474448],
       [0.89528471, 0.10471529],
       [0.06308131, 0.93691869],
       [0.04882793, 0.95117207],
       [0.46170679, 0.53829321],
       [0.55876524, 0.44123476],
       [0.24097909, 0.75902091],
       [0.76325552, 0.23674448],
       [0.086862  , 0.913138  ],
       [0.19216598, 0.80783402],
       [0.

In [9]:
# positive outcomes

model_prob=y_pred_proba[:,1]
model_prob

array([0.8137542 , 0.97355809, 0.00790035, 0.27719514, 0.30924721,
       0.94307797, 0.83934166, 0.89902809, 0.01661477, 0.81903124,
       0.41479858, 0.01328948, 0.88265549, 0.73751064, 0.01958081,
       0.80646271, 0.03757978, 0.39153523, 0.96644436, 0.00369815,
       0.63474448, 0.10471529, 0.93691869, 0.95117207, 0.53829321,
       0.44123476, 0.75902091, 0.23674448, 0.913138  , 0.80783402,
       0.66389029, 0.96805651, 0.96354022, 0.03015034, 0.68660116,
       0.9818972 , 0.48124545, 0.10096633, 0.99805147, 0.20275541,
       0.24768163, 0.989197  , 0.22023911, 0.0485996 , 0.90225498,
       0.91103958, 0.04238465, 0.0977924 , 0.1233309 , 0.85664884,
       0.68714277, 0.20689254, 0.96061864, 0.74310178, 0.84615876,
       0.26771994, 0.09506259, 0.42477405, 0.80634783, 0.89620116,
       0.00119135, 0.36058555, 0.5408668 , 0.00864359, 0.00680325,
       0.77306106, 0.15771742, 0.01875076, 0.22535316, 0.79053443,
       0.7916915 , 0.05746974, 0.76047013, 0.92458715, 0.00896

In [13]:
# calculating roc auc score

dummy_model_auc=roc_auc_score(y_test, dummy_prob)
model_auc=roc_auc_score(y_test, y_pred_proba)
print(dummy_model_auc)
print(model_auc)

ValueError: y should be a 1d array, got an array of shape (200, 2) instead.

In [17]:
# plotting the ROC curve 

dummy_fpr,dummy_tpr, _ =roc_curve(y_test, dummy_prob)
model_fpr, model_tpr, thresholds =roc_curve(y_test, y_pred_proba)

ValueError: y should be a 1d array, got an array of shape (200, 2) instead.

In [14]:
dummy_prob

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [15]:
model_prob

array([0.8137542 , 0.97355809, 0.00790035, 0.27719514, 0.30924721,
       0.94307797, 0.83934166, 0.89902809, 0.01661477, 0.81903124,
       0.41479858, 0.01328948, 0.88265549, 0.73751064, 0.01958081,
       0.80646271, 0.03757978, 0.39153523, 0.96644436, 0.00369815,
       0.63474448, 0.10471529, 0.93691869, 0.95117207, 0.53829321,
       0.44123476, 0.75902091, 0.23674448, 0.913138  , 0.80783402,
       0.66389029, 0.96805651, 0.96354022, 0.03015034, 0.68660116,
       0.9818972 , 0.48124545, 0.10096633, 0.99805147, 0.20275541,
       0.24768163, 0.989197  , 0.22023911, 0.0485996 , 0.90225498,
       0.91103958, 0.04238465, 0.0977924 , 0.1233309 , 0.85664884,
       0.68714277, 0.20689254, 0.96061864, 0.74310178, 0.84615876,
       0.26771994, 0.09506259, 0.42477405, 0.80634783, 0.89620116,
       0.00119135, 0.36058555, 0.5408668 , 0.00864359, 0.00680325,
       0.77306106, 0.15771742, 0.01875076, 0.22535316, 0.79053443,
       0.7916915 , 0.05746974, 0.76047013, 0.92458715, 0.00896