### Numpy
Numpy is the fundamental library for scientific computing in Python. It provides support for arrays and matrices along with a set of mathematical operations that work on these data structures.

#### Numpy Basics

In [1]:
# importing numpy
import numpy as np

In [5]:
# creating a numpy array
arr1=np.array([1,2,3,4,5])   # 1-D Array
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


In [6]:
arr2=np.array([[1,2,3,4,5],
               [6,7,8,9,0]]) # 2-D Array
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [9]:
np.arange(0,10,2).reshape(5,1)  # np.arange(start, end, step-up)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,3))   # matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(5)   # creates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Numpy Fundamental Operations

In [13]:
arr2.size  # prints number of elements in the array

10

In [14]:
arr2.ndim  # prints the number of dimensions in the array

2

In [15]:
arr2.dtype  # prints the data-type of the elements in the array 

dtype('int64')

In [16]:
arr2.itemsize # prints the size of the elements in the array in bytes

8

In [17]:
# Vectorized Operation in NumPy (element-wise operations)
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,0])

# Vector Addition
print("Sum=",arr1+arr2)
# Vector Subtraction
print("Difference=",arr2-arr1)
# Vector Multiplication
print("Product=",arr1*arr2)
# Vector Division
print("Quotient=",arr2/arr1)

Sum= [ 7  9 11 13  5]
Difference= [ 5  5  5  5 -5]
Product= [ 6 14 24 36  0]
Quotient= [6.         3.5        2.66666667 2.25       0.        ]


In [19]:
# Universal Functions
arr=np.array([2,5,3,8,1])

# Square
print(np.square(arr))
# Square Root
print(np.sqrt(arr))
# Exponential
print(np.exp(arr))
# Sine
print(np.sin(arr))
# Log
print(np.log10(arr))

[ 4 25  9 64  1]
[1.41421356 2.23606798 1.73205081 2.82842712 1.        ]
[7.38905610e+00 1.48413159e+02 2.00855369e+01 2.98095799e+03
 2.71828183e+00]
[ 0.90929743 -0.95892427  0.14112001  0.98935825  0.84147098]
[0.30103    0.69897    0.47712125 0.90308999 0.        ]


In [36]:
# Slicing Array Elements
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [37]:
# Slicing 2,3,7,8
print(arr[0:,1:3])   # arr[row-slicing, column-slicing]

[[2 3]
 [7 8]]


In [38]:
# Slicing 4,5,9,0
print(arr[0:,3:])

[[4 5]
 [9 0]]


In [39]:
# Modifying Array Elements
arr[1,2]=505
print(arr)

[[  1   2   3   4   5]
 [  6   7 505   9   0]]


In [40]:
arr[0:,]=6969
arr

array([[6969, 6969, 6969, 6969, 6969],
       [6969, 6969, 6969, 6969, 6969]])

#### Statistical Operations with NumPy

In [41]:
# Statistical Operations with NumPy
data=np.array([1,2,3,4,5])

# Mean
mean=np.mean(data)
# Standard Deviation
std_dev=np.std(data)
# Median
median=np.median(data)
# Variance
variance=np.var(data)
# Norma;izing the Data (normalized data: mean=1 standard deviation=0)
normalized_data=(data-mean)/std_dev

print('Mean:',mean)
print('Variance:',variance)
print('Standard Deviation:',std_dev)
print('Median:',median)
print('Normalized Data:',normalized_data)


Mean: 3.0
Variance: 2.0
Standard Deviation: 1.4142135623730951
Median: 3.0
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [43]:
# Logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data[(data>7) & (data<9)])  # We can only use logical operations here ('and','or' is not allowed)

[8]
