In [1]:
# importing basic libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec, KeyedVectors

In [5]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['King']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [6]:
vec_king

array([-0.00350952,  0.01623535, -0.08154297,  0.12792969,  0.11230469,
       -0.00534058,  0.03063965,  0.04931641,  0.22070312,  0.07373047,
       -0.13769531,  0.16210938,  0.02148438, -0.09375   , -0.12792969,
       -0.12402344, -0.11132812,  0.11816406, -0.07861328,  0.25390625,
        0.01794434,  0.14160156,  0.0612793 , -0.08691406,  0.07763672,
        0.05175781, -0.24609375, -0.17578125,  0.14746094,  0.06640625,
       -0.03833008, -0.09033203, -0.07226562,  0.09375   , -0.18847656,
        0.06347656,  0.24121094,  0.00714111, -0.30273438, -0.02478027,
       -0.09619141, -0.30859375, -0.06054688,  0.22167969,  0.07763672,
        0.05834961,  0.15527344, -0.13476562, -0.00341797, -0.13964844,
       -0.02905273,  0.03833008, -0.15332031, -0.20996094,  0.21679688,
        0.01171875, -0.078125  ,  0.00402832, -0.23535156, -0.10400391,
        0.08837891,  0.25976562,  0.02709961,  0.01123047,  0.12988281,
       -0.11914062, -0.07861328, -0.04736328, -0.06591797,  0.07

In [7]:
vec_king.shape

(300,)

In [8]:
wv['football']

array([-9.76562500e-02,  3.19824219e-02,  2.57812500e-01, -4.15039062e-02,
        1.01562500e-01, -1.00585938e-01,  1.46484375e-01, -1.99218750e-01,
        1.53320312e-01,  6.34765625e-02,  8.39843750e-02, -3.00781250e-01,
        6.34765625e-02,  2.08984375e-01, -2.11914062e-01,  1.88476562e-01,
       -8.34960938e-02,  3.28125000e-01,  2.79296875e-01, -1.40625000e-01,
       -1.68945312e-01,  2.04101562e-01,  4.90722656e-02, -6.98852539e-03,
        9.42382812e-02,  9.84191895e-04,  3.12500000e-02,  2.48046875e-01,
        3.35937500e-01,  2.63671875e-01,  5.68847656e-02,  3.04687500e-01,
        1.21582031e-01, -1.97265625e-01,  1.72119141e-02,  9.96093750e-02,
        2.27539062e-01, -1.20605469e-01,  1.23535156e-01,  3.78906250e-01,
        2.36816406e-02, -1.86523438e-01,  6.29882812e-02,  1.52343750e-01,
        3.73535156e-02, -1.69921875e-01,  1.06445312e-01, -4.98046875e-02,
       -6.20117188e-02,  1.68945312e-01,  4.41894531e-02,  2.78320312e-02,
       -1.10839844e-01,  

In [10]:
wv.most_similar('football')

[('soccer', 0.731354832649231),
 ('fooball', 0.7139959335327148),
 ('Football', 0.7124834060668945),
 ('basketball', 0.668246865272522),
 ('footbal', 0.6649289727210999),
 ('athletics', 0.6265192627906799),
 ('gridiron', 0.6191604733467102),
 ('baseball', 0.6162001490592957),
 ('footballl', 0.6069177389144897),
 ('sports', 0.5927178859710693)]

In [11]:
wv.most_similar('messi')

[('drogba', 0.8152334094047546),
 ('ronaldo', 0.7879914045333862),
 ('ronaldinho', 0.7759475111961365),
 ('torres', 0.7755779027938843),
 ('pirlo', 0.7746129631996155),
 ('xavi', 0.7720138430595398),
 ('sneijder', 0.7672234177589417),
 ("eto'o", 0.7641000151634216),
 ('barca', 0.7615001797676086),
 ('gerrard', 0.7611674070358276)]

In [13]:
vec=wv['king']-wv['man']+wv['woman']

In [14]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [15]:
wv.most_similar(vec)

[('king', 0.8449392318725586),
 ('queen', 0.7300516366958618),
 ('monarch', 0.6454660296440125),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676948547363),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376776456832886),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]